#!/bin/bash

DEFAULT_TARGET_DIR="../../../"
DEFAULT_PROCESS_COUNT=1
DEFAULT_TEST_COUNT=1
DEFAULT_TEST_SYNC='true'
DEFAULT_THREAD_COUNT=0
DEFAULT_BOUND_OPTION=0
DEFAULT_USE_ORT_OPTION=off

TARGET_DIR=${1:-$DEFAULT_TARGET_DIR}
PROCESS_COUNT=${2:-$DEFAULT_PROCESS_COUNT}
TEST_COUNT=${3:-$DEFAULT_TEST_COUNT}
TEST_SYNC=${4:-$DEFAULT_TEST_SYNC}
THREAD_COUNT=${5:-$DEFAULT_THREAD_COUNT}
BOUND_OPTION=${6:-$DEFAULT_BOUND_OPTION}
USE_ORT_OPTION=${7:-$DEFAULT_USE_ORT_OPTION}

COMMAND='dxrt_test_bit_match'
#MODEL_PATH='/mnt/regression_storage/ci-data/bitmatch_data_set/M1A/YOLOv7_512-YOLOV7-4/YOLOv7_512.dxnn'
MODEL_PATH='/home/sjkim/Development/Assets/models/YOLOv7_512:YOLOV7-4/YOLOv7_512.dxnn'

$TARGET_DIR$COMMAND $MODEL_PATH $PROCESS_COUNT $TEST_COUNT $TEST_SYNC $THREAD_COUNT $USE_ORT_OPTION $BOUND_OPTION


